### ISSUE TITLE
URLResolver errors when receiving messages

### ISSUE THREAD

**Issue by jolsen71** [abhishek-ram/django-pyas2#17]
When the instance receives a message attempt (either from another testing django-pyas2 I have or from a real third party partner), I am getting the following errors in the logs with DEBUG logging level:

```Exception while resolving variable 'name' in template 'unknown'.
 Traceback (most recent call last):
  File "/projects/as2/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/projects/as2/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/projects/as2/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 566, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
 django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'pyas2.urls' from '/projects/as2/env/lib/python3.6/site-packages/pyas2/urls.py'> (None:None) 'pyas2/'>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>]], 'path': ''}

 During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/as2/env/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
 TypeError: 'URLResolver' object is not subscriptable
```
and
 
```Traceback (most recent call last):
   File "/raid/0/www/docs/projects/as2/env/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
     current = getattr(current, bit)
 AttributeError: 'URLResolver' object has no attribute 'name'
```

and

```Traceback (most recent call last):
  File "/raid/0/www/docs/projects/as2/env/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
 ValueError: invalid literal for int() with base 10: 'name'
```
 
It seems like I am able to successfully send messages from this instance and use the admin URLs with no problem, it just seems to be related to receiving messages.

I don't believe I've done anything wrong following the installation/quickstart instructions, but since nobody has seemingly ran into this issue, I'm not sure. 

Please advise. 

Thanks

**Comment by abhishek-ram** [comment]
Can you show me the contents of your `urls.py`

**Comment by jolsen71** [comment]
Omitting comments, here is my `urls.py`
```
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('pyas2/', include('pyas2.urls')),
    path('admin/', admin.site.urls),
]
```

**Comment by jolsen71** [comment]
results of `pip freeze`
```
asn1crypto==0.24.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
cryptography==2.7
dataclasses==0.6
Django==2.2.4
django-pyas2==1.1.1
idna==2.8
oscrypto==0.19.1
pyas2lib==1.2.2
pycparser==2.19
pyOpenSSL==17.5.0
pytz==2019.1
requests==2.22.0
six==1.12.0
sqlparse==0.3.0
urllib3==1.25.3
```

**Comment by jolsen71** [comment]
Would someone please share their `pip freeze` results (if different than mine) and I'll see if locking versions of all python modules works around this blocking issue for me? 

If you have the same versions of everything in your  `pip freeze` output and your instance of django-pyas2 is fully functional, please also let me know that it is somehow not a module version difference.

Thanks

**Comment by abhishek-ram** [comment]
I was checking on this error and it seems a non issue, can you tell me what http code is returned when you try to open the receive link and also let me know the url

**Comment by duaneking** [comment]
The error says you have a template with the 'name' tag in it that is not being set by your context on render.
