### ISSUE TITLE
TypeError: 'unicode' does not have the buffer interface

### ISSUE THREAD

**Issue by Xbeninni** [abhishek-ram/django-pyas2#9]
I'm following the [Quickstart](https://django-pyas2.readthedocs.io/en/latest/quickstart.html) to send a test message between P1 and P2. I got this error when I hit the Send Message button.

```
Performing system checks...

System check identified no issues (0 silenced).
June 08, 2019 - 12:52:31
Django version 1.11.21, using settings 'django_pyas2.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /pyas2/as2send/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/usr/local/lib/python2.7/dist-packages/pyas2/views.py", line 207, in form_valid
    content_type=form.cleaned_data['partner'].content_type
  File "/usr/local/lib/python2.7/dist-packages/pyas2lib-1.1.0-py2.7.egg/pyas2lib/as2.py", line 402, in build
    mic_content = canonicalize(self.payload)
  File "/usr/local/lib/python2.7/dist-packages/pyas2lib-1.1.0-py2.7.egg/pyas2lib/utils.py", line 78, in canonicalize
    return mime_to_bytes(message, 0).replace(
  File "/usr/local/lib/python2.7/dist-packages/pyas2lib-1.1.0-py2.7.egg/pyas2lib/utils.py", line 58, in mime_to_bytes
    g.flatten(msg)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib/python2.7/email/generator.py", line 145, in _write_headers
    print >> self._fp, v
TypeError: 'unicode' does not have the buffer interface
[08/Jun/2019 12:53:08] "POST /pyas2/as2send/?partner_id=p2as2 HTTP/1.1" 500 107315
```

**Comment by abhishek-ram** [comment]
You are using python version 2.7 but pyas2 supports only version 3.5+

**Comment by Xbeninni** [comment]
> You are using python version 2.7 but pyas2 supports only version 3.5+

Thank you @abhishek-ram  , I appreciate it.   It indicates in the [doc](https://django-pyas2.readthedocs.io/en/latest/)  that [django-pyas2](https://django-pyas2.readthedocs.io/en/latest/) supports Python 2.6-2.7. So, maybe you will consider an update there.

Actually I moved from your other great repository [pyas2](https://github.com/abhishek-ram/pyas2). Pyas2 support Python 2.6-2.7.  I was thing that it would be wonderful it Pyas2 support Python3.x, now  [django-pyas2](https://django-pyas2.readthedocs.io/en/latest/) make it real. I can't believe that, thank you so much for your great work!

**Comment by Xbeninni** [comment]
@abhishek-ram   Hello Abhishek, it looks like you are using Django2x for django-pas2, so the url setting in the [installation guide](https://django-pyas2.readthedocs.io/en/latest/installation.html) could be:

```
from django.conf.urls import include
path('pyas2/', include('pyas2.urls')),
```

instead of 
```
from django.conf.urls import include
url(r'^pyas2/', include('pyas2.urls')),
```

**Comment by abhishek-ram** [comment]
thanks @Xbeninni I will update the doc accordingly.
